// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZnG5BdP0YJd_OhmYJCy8CbKEj2g5Ko8I',
    appId: '1:732020516241:web:321325597a8bade0786630',
    messagingSenderId: '732020516241',
    projectId: 'angular-host-c05fb',
    authDomain: 'angular-host-c05fb.firebaseapp.com',
    databaseURL: 'https://angular-host-c05fb-default-rtdb.firebaseio.com',
    storageBucket: 'angular-host-c05fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEvo0BMm17JZOtZxODSoGfbbPTAYaFkVE',
    appId: '1:732020516241:android:e814889008282f2e786630',
    messagingSenderId: '732020516241',
    projectId: 'angular-host-c05fb',
    databaseURL: 'https://angular-host-c05fb-default-rtdb.firebaseio.com',
    storageBucket: 'angular-host-c05fb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZnG5BdP0YJd_OhmYJCy8CbKEj2g5Ko8I',
    appId: '1:732020516241:web:faacbba658b06e26786630',
    messagingSenderId: '732020516241',
    projectId: 'angular-host-c05fb',
    authDomain: 'angular-host-c05fb.firebaseapp.com',
    databaseURL: 'https://angular-host-c05fb-default-rtdb.firebaseio.com',
    storageBucket: 'angular-host-c05fb.firebasestorage.app',
  );

}